name: Build and Deploy 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - rentalService/**

defaults:
  run:
    working-directory: rentalService

jobs:
  build:
    name: Build Rental Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test
        run: ./gradlew build

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}