name: Build and Deploy 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - rentalService/**

defaults:
  run:
    working-directory: rentalService

jobs:
  test:
    name: Build Rental Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        run: ./gradlew build
